version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
      - ./backend/data:/app/data
    environment:
      - PORT=5001
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
