name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js for backend
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache backend node_modules
      uses: actions/cache@v3
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-node-backend-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-backend-

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run backend tests
      working-directory: ./backend
      run: npm test || echo "No backend tests defined"

    - name: Setup Node.js for frontend
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache frontend node_modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-frontend-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-frontend-

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test || echo "No frontend tests defined"

  docker-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environnement: DOCKER_USERNAME

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t anthonydos/backend:latest ./backend

      - name: Build frontend image
        run: docker build -t anthonydos/frontend:latest ./frontend

      - name: Push backend image
        run: docker push anthonydos/backend:latest

      - name: Push frontend image
        run: docker push anthonydos/frontend:latest

